config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, except: :show do
    resources :comments
  end

  resources :friend_requests, only: [:index, :create] do
    put :accept, to: 'friend_requests#accept'
    delete :decline, to: 'friend_requests#decline'
    delete :unfriend, to: 'friend_requests#unfriend'
    delete :cancel, to: 'friend_requests#cancel'
  end

  resources :user_groups, only: :index do
    put :accept, to: 'user_groups#accept'
    put :leave, to: 'user_groups#leave'
    put :approve, to: 'user_groups#approve'
    put :decline, to: 'user_groups#decline'
    put :change_role, to: 'user_groups#change_role'
    put 'change_suspension/:is_suspended', as: :change_suspension, to: 'user_groups#change_suspension'
    put :remove, to: 'user_groups#remove'
  end

  resources :groups, except: :index do
    resources :posts, except: :index, controller: "group_posts" do
      resources :comments
      put :remove, to: 'group_posts#remove'
      get :show_remove, to: 'group_posts#show_remove'
      put :reject, to: 'group_posts#reject'
      put :publish, to: 'group_posts#publish'
    end
    post :join, to: 'groups#join'
    get :home
    post 'invite/:user_id', as: :invite, to: 'groups#invite'
    get :invite_friends, to: 'groups#invite_friends'
    get :member_management, to: 'groups#member_management'
    get :post_management, to: 'groups#post_management'
    put 'change_privacy/:privacy', as: :change_privacy, to: 'groups#change_privacy'
  end

  root :to => 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/group_posts_controller.rb
class GroupPostsController < PostsController
  before_action :set_group

  def create
    post_params[:group_id] = @group.id
    super
  end

  def publish
    authorize @post, :publish?, policy_class: GroupPostPolicy
    if @post.may_publish? @post.publish!
      flash[:notice] = 'Successfully accepted'
    else
      flash[:alert] = @post.errors.full_messages.join(', ')
    end
    redirect_to request.referrer || group_home_path(@group)
  end

  def show_remove
    authorize @post, :show_remove?, policy_class: GroupPostPolicy
  end

  def remove
    authorize @post, :remove?, policy_class: GroupPostPolicy
    if @post.may_remove? @post.remove!
      flash[:notice] = 'Successfully accepted'
    else
      flash[:alert] = @post.errors.full_messages.join(', ')
    end
    redirect_to group_home_path(@group)
  end

  def reject
    authorize @post, :reject?, policy_class: GroupPostPolicy
    if @post.may_reject? @post.reject!
      flash[:notice] = 'Successfully rejected'
    else
      flash[:alert] = @post.errors.full_messages.join(', ')
    end
    redirect_to group_post_management_path(management: 'Pending Posts')
  end

  private

  def set_post
    @post = Post.find(params[:id] || params[:post_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
    authorize @group, :member?, policy_class: GroupPostPolicy
  end

  def default_posts_path
    group_home_path(@group)
  end
end

app/views/group_posts/_form.html.erb
<style>
    p {
        font-size: 12px;
        margin-bottom: 4px
    }
</style>


<% if @display_address.present? %>
  <span class="badge bg-primary"><%= @display_address %></span>
    <div class="field">
      <div class="form-check form-switch">
        <%= check_box_tag :share_geo_location, 'true', @post.location.present?, class:"form-check-input", role:"switch"%>
        <label class="form-check-label">Share my location</label>
      </div>
    </div>
<% end %>

<div class="text-center">
  <%= image_tag "", id:"previewImg", class:"w-25 my-2 d-none", style:"object-fit: cover"%>
  <%= image_tag post.image.url, class:"original w-25 my-2", style:"object-fit: cover" if post.image?%>
  <div class="field">
    <%= f.label :image, "change image", class: "btn btn-dark" %>
    <%= f.file_field :image, class: 'form-control d-none', onchange: "previewFile(this)" %>
    <%= content_tag :p, post.errors.full_messages_for(:image).join(', '), class: 'text-danger m-1' if post.errors.has_key?(:image) %>
  </div>
</div>

<div class="field">
  <%= f.label :text %>
  <%= f.text_field  :text , class: 'form-control' %>
  <%= content_tag :p, post.errors.full_messages_for(:text).join(', '), class: 'text-danger m-1' if post.errors.has_key?(:text) %>
</div>

<script>
    function previewFile(input) {
        var file = $("input[type=file]").get(0).files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function () {
                $("#previewImg").attr("src", reader.result);
                $("#previewImg").css('display', 'block');
                $(".original").css('display', 'none');
            }
            reader.readAsDataURL(file);
        }
    }
</script>

app/views/group_posts/edit.html.erb
<!--Page-->
<div class="container">
  <div class="card">
    <div class="card-header">
      <%= link_to "❮ Back", posts_path, class: 'btn btn-sm btn-outline-primary d-inline-block ' %>
      <h5 class="d-inline-block align-middle mx-2 my-1">Edit Post</h5>
    </div>
    <div class="card-body">
      <%= form_for @post, url: group_post_path(@group), method: :patch do |f| %>
        <%= render partial: 'form', locals: { f: f, post: @post } %>
        <%= f.submit "Update", class: 'border btn btn-primary form-control mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/group_posts/new.html.erb
<!--Page-->
<div class="container">
  <div class="card">
    <div class="card-header">
      <%= link_to "❮ Back", posts_path, class: 'btn btn-sm btn-outline-primary d-inline-block '%>
      <h5 class="d-inline-block align-middle mx-2 my-1">Create Post</h5>
    </div>
    <div class="card-body">
      <%= form_for @post, url: group_posts_path(@group), method: :post do |f| %>
        <%= render partial: 'form', locals: {f: f, post: @post} %>
        <%= f.submit "Create", class: 'border btn btn-primary form-control mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/group_posts/show_remove.html.erb
<%= form_for @post, url: group_post_remove_path(@group, @post), method: :put  do |f| %>
    <%= f.label :remarks, "remarks"%>
    <%= f.text_area :remarks %>
    <%= f.submit "Remove", class: 'text-light btn form-control' %>
<% end %>