config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, except: :show do
    resources :comments
  end

  resources :friend_requests, only: [:index, :create] do
    put :accept, to: 'friend_requests#accept'
    delete :decline, to: 'friend_requests#decline'
    delete :unfriend, to: 'friend_requests#unfriend'
    delete :cancel, to: 'friend_requests#cancel'
  end

  resources :user_groups, only: :index do
    put :accept, to: 'user_groups#accept'
    put :leave, to: 'user_groups#leave'
    put :approve, to: 'user_groups#approve'
    put :decline, to: 'user_groups#decline'
    put :change_role, to: 'user_groups#change_role'
    put 'change_suspension/:is_suspended', as: :change_suspension, to: 'user_groups#change_suspension'
    put :remove, to: 'user_groups#remove'
  end

  resources :groups, except: :index do
    resources :posts, except: :index, controller: "group_posts" do
      resources :comments
      put :remove, to: 'group_posts#remove'
      get :show_remove, to: 'group_posts#show_remove'
      put :reject, to: 'group_posts#reject'
      put :publish, to: 'group_posts#publish'
    end
    post :join, to: 'groups#join'
    get :home
    post 'invite/:user_id', as: :invite, to: 'groups#invite'
    get :invite_friends, to: 'groups#invite_friends'
    get :member_management, to: 'groups#member_management'
    get :post_management, to: 'groups#post_management'
    put 'change_privacy/:privacy', as: :change_privacy, to: 'groups#change_privacy'
  end

  root :to => 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :description, :banner, :owner, :can_invite, :privacy, presence: true
  belongs_to :owner, class_name: "User"
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :posts, dependent: :destroy
  enum privacy: [:unrestricted, :restricted]
  after_create :create_user_group_record_for_owner
  mount_uploader :banner, ImageUploader

  def create_user_group_record_for_owner
    owner_user_group = UserGroup.new(user: owner, group: self, roles: :admin, state: :accepted)
    owner_user_group.save!
  end

  def member?(user)
    user_groups.accepted.find_by(user: user).present?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, except: [:new, :create]

  def home
    authorize @group, :home?, policy_class: GroupPolicy
    @posts = @group.posts.published
  end

  def member_management
    authorize @group, :member_management?, policy_class: GroupPolicy
    @pending_member_records = @group.user_groups.includes(:user).pending if params[:management] == 'Pending approval'
    @member_records = policy_scope(@group).includes(:user) if params[:management] != 'Pending approval'
  end

  def post_management
    authorize @group, :post_management?, policy_class: GroupPolicy
    # @reported_posts = xxxxxxxxx if params[:management] == 'Reported posts'
    @pending_posts = @group.posts.includes(:user).pending if params[:management] != 'Reported posts'
  end

  def change_privacy
    authorize @group, :change_privacy?, policy_class: GroupPolicy
    if @group.update(privacy: params[:privacy])
      flash[:notice] = "privacy is succesfully changed to #{params[:privacy]}"
    else
      flash[:alert] = @group.errors.full_messages.join(', ')
    end
    redirect_to group_home_path(@group)
  end

  def new
    @group = Group.new
  end

  def show; end

  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    if @group.save
      flash[:notice] = "Successfully created!"
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def destroy
    authorize @group, :destroy?, policy_class: GroupPolicy
    if @group.destroy
      flash[:notice] = "Your Group is Successfully deleted!"
    else
      flash[:alert] = @group.errors.full_messages.join(', ')
    end
    redirect_to user_groups_path(group_record: 'Find groups')
  end

  def join
    if @user_group = current_user.user_groups.where(state: UserGroup::PREVIOUS_MEMBER_STATES).find_by(group: @group)
      @user_group.roles = :normal
      @user_group.reenter!
      accept_if_unrestricted
    else
      @user_group = UserGroup.new
      @user_group.user = current_user
      @user_group.roles = :normal
      @user_group.group = @group
      if @user_group.save
        accept_if_unrestricted
      else
        flash[:alert] = @user_group.errors.full_messages.join(', ')
      end
    end
    redirect_to user_groups_path(group_record: 'Find groups')
  end

  def invite_friends
    authorize @group, :invite_friends?, policy_class: GroupPolicy
    @uninvited_friends = current_user.friends.where.not(id: @group.user_groups.where(state: [:pending, :accepted]).pluck(:user_id))
  end

  def invite
    @user = User.find(params[:user_id])
    authorize @group, :invite?, policy_class: GroupPolicy
    authorize @user, :friend?, policy_class: UserPolicy
    if @user_group = @user.user_groups.where(state: UserGroup::PREVIOUS_MEMBER_STATES).find_by(group: @group)
      @user_group.inviter = current_user
      @user_group.reenter!
    else
      @user_group = UserGroup.new
      @user_group.user = @user
      @user_group.inviter = current_user
      @user_group.group = @group
      if @user_group.save
        flash[:notice] = "successfully invited"
      else
        flash[:alert] = @user_group.errors.full_messages.join(', ')
      end
    end
    redirect_to group_invite_friends_path
  end

  private

  def accept_if_unrestricted
    if @user_group.group.unrestricted?
      @user_group.accept!
      flash[:notice] = "Successfully joined!"
    else
      flash[:notice] = "request to join is submitted!"
    end
  end

  def set_group
    @group = Group.find(params[:id] || params[:group_id])
  end

  def group_params
    params.require(:group).permit(:name, :banner, :description, :privacy, :can_invite)
  end
end

app/views/groups/home.html.erb
<%= image_tag @group.banner.url, class:"original w-25 my-2", style:"object-fit: cover"%>
<%= @group.name %>
<%= @group.description%>

<%= link_to 'Invite Friends', group_invite_friends_path(@group), class: 'btn btn-primary w-25' %>
<%= link_to 'Member Management', group_member_management_path(@group), class: 'btn btn-primary w-25' if policy(@group).member_management?%>
<%= link_to 'Delete Group', group_path(@group), method: :delete, class: 'btn btn-primary w-25' if policy(@group).destroy?%>
<%= link_to "Make group #{privacy_toggled_value(@group)}", group_change_privacy_path(@group, privacy_toggled_value(@group)), method: :put, class: 'btn btn-primary w-25' if policy(@group).change_privacy?%>
<%= link_to 'Post Management', group_post_management_path(@group), class: 'btn btn-primary w-25' if policy(@group).post_management?%>
<%#= link_to 'Post Management', group_invite_friends_path(@group), class: 'btn btn-primary w-25' %>

<%= link_to 'New Post', new_group_post_path, class: 'btn btn-primary w-25' %>
<div class="card mt-4">
  <div class="card-body ">
    <table class="table table-striped table-hover">
      <thead>
      <th>Image</th>
      <td>text</th>
      <td>city</th>
      <td>district</th>
      <td>province</th>
      <th>Action</th>
      </thead>
      <tbody>

      <% @posts.each do |post| %>
        <tr>
          <td style="width: 200px"><%= image_tag post.image.url, alt: 'avatar', class:'w-100',style:"object-fit: cover" if post.image?%></td>
          <td><%= post.text %></th>
          <td><%= post.city %></th>
          <td><%= post.district %></th>
          <td><%= post.province %></th>
          <td>
            <%= link_to 'comments', group_post_comments_path(@group, post), class: 'btn btn-warning' %>
             <%#= link_to 'report', group_post_comments_path(@group, post), class: 'btn btn-warning' %> 
            <%= link_to 'remove', group_post_show_remove_path(@group, post), class: 'btn btn-warning'%>
            <%= link_to 'edit', edit_group_post_path(@group, post), class: 'btn btn-warning' if post.user == current_user %>
            <%= link_to "delete", group_post_path(@group, post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' if post.user == current_user %>
          </td>
        </tr>
      <% end %>
      <% unless @posts.present?%>
        <tr>
          <td colspan="4" class="text-muted">
            No posts to show
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/groups/invite_friends.html.erb
<table>
<% @uninvited_friends.each do |friend| %>
  <tr>
    <td><%= friend.email %></th>
    <td>
      <%= link_to 'invite', group_invite_path(@group, friend), method: :post, class: 'btn btn-warning' %>
    </td>
  </tr>
<% end %>
<% unless @uninvited_friends.present?%>
  <tr>
    <td colspan="4" class="text-muted">
      No friends to show
    </td>
  </tr>
<% end %>
</table>

app/views/groups/member_management.erb
<table>
  <% ['Manage members', 'Pending approval' ].each do |manage_members| %>
    <%= link_to manage_members, group_member_management_path(management: manage_members), class: "#{:active if params[:manage_members] == manage_members} btn btn-primary" %>
  <% end %>

  <% @member_records&.each do |member_record| %>
    <tr>
      <td><%= member_record.user.email %></th>
      <td>
        <%= link_to member_record.is_suspended ? 'unsuspend' : 'suspend', user_group_change_suspension_path(member_record, is_suspended: member_record.is_suspended ? 0 : 1), method: :put, class: 'btn btn-warning' %>
        <%= link_to 'Remove', user_group_remove_path(member_record), method: :put, class: 'btn btn-warning' if policy(member_record).remove?%>
        <%= form_for member_record, url: user_group_change_role_path(member_record), method: :put  do |f| %>
          <%= f.select :roles, current_user.subordinates(member_record.group).map { |key| [key.to_s.humanize, key] }, { class: 'form-control mt-3' } %>
          <%= f.submit "Assign", class: 'text-light btn form-control' %>
        <% end %>
      </td>
    </tr>
  <% end %>

  <% @pending_member_records&.each do |pending_member| %>
    <tr>
      <td><%= pending_member.user.email %></th>
      <td>
        <%= link_to 'Approve', user_group_approve_path(pending_member), method: :put, class: 'btn btn-warning'%>
      </td>
    </tr>
  <% end %>
</table>

app/views/groups/member_management.html.erb
<table>
  <% ['Manage members', 'Pending approval' ].each do |manage_members| %>
    <%= link_to manage_members, group_member_management_path(management: manage_members), class: "#{:active if params[:manage_members] == manage_members} btn btn-primary" %>
  <% end %>

  <% @member_records&.each do |member_record| %>
    <tr>
      <td><%= member_record.user.email %></th>
      <td>
        <%= link_to member_record.is_suspended ? 'unsuspend' : 'suspend', user_group_change_suspension_path(member_record, is_suspended: member_record.is_suspended ? 0 : 1), method: :put, class: 'btn btn-warning' %>
        <%= link_to 'Remove', user_group_remove_path(member_record), method: :put, class: 'btn btn-warning'%>
        <%= form_for member_record, url: user_group_change_role_path(member_record), method: :put  do |f| %>
          <%= f.select :roles, current_user.subordinates(member_record.group).map { |key| [key.to_s.humanize, key] }, { class: 'form-control mt-3' } %>
          <%= f.submit "Assign", class: 'text-light btn form-control' %>
        <% end %>
      </td>
    </tr>
  <% end %>

  <% @pending_member_records&.each do |pending_member| %>
    <tr>
      <td><%= pending_member.user.email %></th>
      <td>
        <%= link_to 'Approve', user_group_approve_path(pending_member), method: :put, class: 'btn btn-warning'%>
      </td>
    </tr>
  <% end %>
</table>

app/views/groups/new.html.erb
<style>
    p {
        font-size: 12px;
        margin-bottom: 4px
    }
</style>

<div class="container">
  <div class="card">
    <div class="card-header">
      <%= link_to "❮ Back", user_groups_path, class: 'btn btn-sm btn-outline-primary d-inline-block ' %>
      <h5 class="d-inline-block align-middle mx-2 my-1">Create Group</h5>
    </div>
    <div class="card-body">
      <%= form_for @group, url: groups_path(@group), method: :post do |f| %>

        <div class="text-center">
          <%= image_tag "", id: "previewImg", class: "w-25 my-2 d-none", style: "object-fit: cover" %>
          <%= image_tag @group.banner.url, class: "original w-25 my-2", style: "object-fit: cover" if @group.banner? %>
          <div class="field">
            <%= f.label :banner, "change banner", class: "btn btn-dark" %>
            <%= f.file_field :banner, class: 'form-control d-none', onchange: "previewFile(this)" %>
            <%= content_tag :p, @group.errors.full_messages_for(:banner).join(', '), class: 'text-danger m-1' if @group.errors.has_key?(:banner) %>
          </div>
        </div>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
          <%= content_tag :p, @group.errors.full_messages_for(:name).join(', '), class: 'text-danger m-1' if @group.errors.has_key?(:name) %>
        </div>

        <div class="field">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>
          <%= content_tag :p, @group.errors.full_messages_for(:description).join(', '), class: 'text-danger m-1' if @group.errors.has_key?(:description) %>
        </div>

        <div class="field">
          <%= f.label :privacy %>
          <%= f.select :privacy, Group.privacies.keys.map { |key| [key.humanize, key] }, { :prompt => 'Genre' }, class: 'form-control  form-control-sm' %>
          <%= content_tag :p, @group.errors.full_messages_for(:privacy).join(', '), class: 'text-danger m-1' if @group.errors.has_key?(:privacy) %>
        </div>

        <div class="field">
          <%= f.label :can_invite %>
          <%= f.check_box :can_invite %>
          <%= content_tag :p, @group.errors.full_messages_for(:can_invite).join(', '), class: 'text-danger m-1' if @group.errors.has_key?(:can_invite) %>
        </div>

        <%= f.submit "Create", class: 'border btn btn-primary form-control mt-3' %>
      <% end %>
    </div>
  </div>
</div>

<script>
    function previewFile(input) {
        var file = $("input[type=file]").get(0).files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function () {
                $("#previewImg").attr("src", reader.result);
                $("#previewImg").css('display', 'block');
                $(".original").css('display', 'none');
            }
            reader.readAsDataURL(file);
        }
    }
</script>

app/views/groups/post_management.html.erb
  <% ['Pending posts', 'Reported posts' ].each do |manage_posts| %>
    <%= link_to manage_posts, group_post_management_path(management: manage_posts), class: "#{:active if params[:manage_posts] == manage_posts} btn btn-primary" %>
  <% end %>
<table>
    <tbody>
    <% @pending_posts&.each do |pending_post| %>
        <tr>
        <td><%= pending_post.user.email %></td>
            <td style="width: 200px"><%= image_tag pending_post.image.url, alt: 'avatar', class:'w-100',style:"object-fit: cover" if pending_post.image?%></td>
            <td><%= pending_post.text %></th>
            <td><%= pending_post.city %></th>
            <td><%= pending_post.district %></th>
            <td><%= pending_post.province %></th>
            <%= link_to 'Approve', group_post_publish_path(@group, pending_post), method: :put, class: 'btn btn-warning'%>
            <%= link_to 'Reject', group_post_reject_path(@group, pending_post), method: :put, class: 'btn btn-warning'%>
        </td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/groups/show.html.erb
<%= image_tag @group.banner.url, class:"original w-25 my-2", style:"object-fit: cover"%>
<%= @group.name %>
<%= @group.description%>
<%= link_to 'group home', group_home_path(@group), class: 'btn btn-warning' if policy(@group).home?%>