config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, except: :show do
    resources :comments
  end

  resources :friend_requests, only: [:index, :create] do
    put :accept, to: 'friend_requests#accept'
    delete :decline, to: 'friend_requests#decline'
    delete :unfriend, to: 'friend_requests#unfriend'
    delete :cancel, to: 'friend_requests#cancel'
  end

  resources :user_groups, only: :index do
    put :accept, to: 'user_groups#accept'
    put :leave, to: 'user_groups#leave'
    put :approve, to: 'user_groups#approve'
    put :decline, to: 'user_groups#decline'
    put :change_role, to: 'user_groups#change_role'
    put 'change_suspension/:is_suspended', as: :change_suspension, to: 'user_groups#change_suspension'
    put :remove, to: 'user_groups#remove'
  end

  resources :groups, except: :index do
    resources :posts, except: :index, controller: "group_posts" do
      resources :comments
      put :remove, to: 'group_posts#remove'
      get :show_remove, to: 'group_posts#show_remove'
      put :reject, to: 'group_posts#reject'
      put :publish, to: 'group_posts#publish'
    end
    post :join, to: 'groups#join'
    get :home
    post 'invite/:user_id', as: :invite, to: 'groups#invite'
    get :invite_friends, to: 'groups#invite_friends'
    get :member_management, to: 'groups#member_management'
    get :post_management, to: 'groups#post_management'
    put 'change_privacy/:privacy', as: :change_privacy, to: 'groups#change_privacy'
  end

  root :to => 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :receiver, class_name: "User"

  validate :friend_request_unique?, on: :create
  validate :reject_self_request, on: :create

  enum state: [:pending, :accepted]

  def friend_request_unique?
    if user.associated_users.include? receiver
      errors.add(:base, "You and #{receiver.email} are either already friend or has a pending request")
    end
  end

  def reject_self_request
    if user == receiver
      errors.add(:base, "User can't be requested")
    end
  end

  def associated_user(viewer)
    if viewer == user
      receiver
    else
      user
    end
  end

end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :create]
  before_action :set_friend_request, except: [:index, :create]

  def index
    @friend_requests = current_user.all_requests.accepted if params[:request_state] == 'Friends'
    @friend_requests = current_user.requests_sent.pending if params[:request_state] == 'Requests sent'
    @friend_requests = current_user.requests_received.pending if params[:request_state] == 'Requests received'
    @non_associated_users = User.where.not(id: current_user.associated_users).where.not(id: current_user) if @friend_requests.nil?
  end

  def create
    @friend_request = FriendRequest.new
    @friend_request.user = current_user
    @friend_request.receiver_id = params[:receiver_id]
    @friend_request.state = :pending
    if @friend_request.save
      flash[:notice]= 'Successfully Created'
    else
      flash[:alert] = @friend_request.errors.full_messages.join(', ')
    end
    redirect_to request.referrer || friend_requests_path(request_state: 'Find friends')
  end

  def accept
    authorize @friend_request, :accept?, policy_class: FriendRequestPolicy
    if @friend_request.update(state: :accepted)
      flash[:notice] = 'Successfully Added'
    else
      flash[:alert] = @friend_request.errors.full_messages.join(', ')
    end
    redirect_to request.referrer || friend_requests_path(request_state: 'Find friends')
  end

  def decline
    authorize @friend_request, :decline?, policy_class: FriendRequestPolicy
    if @friend_request.destroy
      flash[:notice] = "the request has been declined!"
    else
      flash[:alert] = @friend_request.errors.full_messages.join(', ')
    end
    redirect_to request.referrer || friend_requests_path(request_state: 'Find friends')
  end

  def cancel
    authorize @friend_request, :cancel?, policy_class: FriendRequestPolicy
    if @friend_request.destroy
      flash[:notice] = "the request has been cancelled!"
    else
      flash[:alert] = @friend_request.errors.full_messages.join(', ')
    end
    redirect_to request.referrer || friend_requests_path(request_state: 'Find friends')
  end

  def unfriend
    authorize @friend_request, :unfriend?, policy_class: FriendRequestPolicy
    if @friend_request.destroy
      flash[:notice] = "#{@friend_request.associated_user(current_user).email} has been removed from your friends list!"
    else
      flash[:alert] = @friend_request.errors.full_messages.join(', ')
    end
    redirect_to request.referrer || friend_requests_path(request_state: 'Find friends')
  end

  private

  def set_friend_request
    @friend_request = FriendRequest.find(params[:friend_request_id])
  end
end

app/views/friend_requests/index.html.erb
<div class="mb-2">
  <%= current_user.email %>
  <% User::REQUEST_STATES.each do |request_state| %>
    <%= link_to request_state, friend_requests_path(request_state: request_state), class: "#{:active if params[:request_state] == request_state} btn btn-primary" %>
  <% end %>

  <% @non_associated_users&.each do |non_associated_user| %>
    <%= non_associated_user.email %>
    <%= link_to 'Add Friend', friend_requests_path(receiver_id: non_associated_user), method: :post, class: "btn btn-primary"%>
  <% end %>

  <% @friend_requests&.each do |friend_request| %>
    <%= friend_request.associated_user(current_user).email %>
    <%= link_to :accept, friend_request_accept_path(friend_request), method: :put, class: "btn btn-primary" if policy(friend_request).accept?%>
    <%= link_to :decline, friend_request_decline_path(friend_request), method: :delete, class: "btn btn-primary" if policy(friend_request).decline?%>
    <%= link_to :unfriend, friend_request_unfriend_path(friend_request), method: :delete, class: "btn btn-primary" if policy(friend_request).unfriend?%>
    <%= link_to :cancel, friend_request_cancel_path(friend_request), method: :delete, class: "btn btn-primary" if policy(friend_request).cancel?%>
  <% end %>
</div>