config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, except: :show do
    resources :comments
  end

  resources :friend_requests, only: [:index, :create] do
    put :accept, to: 'friend_requests#accept'
    delete :decline, to: 'friend_requests#decline'
    delete :unfriend, to: 'friend_requests#unfriend'
    delete :cancel, to: 'friend_requests#cancel'
  end

  resources :user_groups, only: :index do
    put :accept, to: 'user_groups#accept'
    put :leave, to: 'user_groups#leave'
    put :approve, to: 'user_groups#approve'
    put :decline, to: 'user_groups#decline'
    put :change_role, to: 'user_groups#change_role'
    put 'change_suspension/:is_suspended', as: :change_suspension, to: 'user_groups#change_suspension'
    put :remove, to: 'user_groups#remove'
  end

  resources :groups, except: :index do
    resources :posts, except: :index, controller: "group_posts" do
      resources :comments
      put :remove, to: 'group_posts#remove'
      get :show_remove, to: 'group_posts#show_remove'
      put :reject, to: 'group_posts#reject'
      put :publish, to: 'group_posts#publish'
    end
    post :join, to: 'groups#join'
    get :home
    post 'invite/:user_id', as: :invite, to: 'groups#invite'
    get :invite_friends, to: 'groups#invite_friends'
    get :member_management, to: 'groups#member_management'
    get :post_management, to: 'groups#post_management'
    put 'change_privacy/:privacy', as: :change_privacy, to: 'groups#change_privacy'
  end

  root :to => 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  validates :text, presence: true
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :group, optional: true
  belongs_to :admin, optional: true
  belongs_to :report, optional: true

  enum audience: [:everyone, :friends_only, :only_me]

  after_create :publish_managers_post

  mount_uploader :image, ImageUploader

  def location
    [city, district, province].reject(&:blank?).join(", ")
  end

  include AASM
  aasm column: :state do
    state :pending, initial: true
    state :published, :removed, :rejected

    event :publish do
      transitions from: :pending, to: :published
    end

    event :remove do
      transitions from: :published, to: :removed
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end
  end

  def publish_managers_post
    return if group.nil?
    unless user.user_groups.find_by(group: group).normal?
      publish!
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: :index
    before_action :set_post, except: [:index, :create, :new]
    before_action :set_geo_location, only: [:new, :create]
    after_action :verify_authorized, except: [:index, :new, :create]

    def index
      @posts = (current_user.posts).or(Post.everyone).or(Post.where(user: current_user.friends).friends_only).order(id: :desc) if current_user
      @posts = Post.everyone.order(id: :desc) unless current_user
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if params[:share_geo_location ] == 'true'
        @post.city = @client_location['city']
        @post.district = @client_location['district']
        @post.province = @client_location['state_prov']
      end
      @post.user = current_user
      @post.group = @group
      if @post.save
        flash[:notice] = "Successfully created!"
        redirect_to default_posts_path
      else
        render :new
      end
    end

    def edit
      authorize @post, :edit?, policy_class: PostPolicy
      @display_address = @post.location
    end

    def update
      authorize @post, :update?, policy_class: PostPolicy
      if params[:share_geo_location ].blank?
        @post.city = nil
        @post.district = nil
        @post.province = nil
      end
      if @post.update(post_params)
        flash[:notice] = "Successfully updated!"
        redirect_to default_posts_path
      else
        render :edit
      end
    end

    def destroy
      authorize @post, :destroy?, policy_class: PostPolicy
      if @post.destroy
        flash[:notice] = "Successfully deleted!"
      else
        flash[:alert] = @post.errors.full_messages.join(', ')
      end
      redirect_to default_posts_path
    end

    private

    def post_params
      params.require(:post).permit(:image, :text, :audience)
    end

    def set_geo_location
      @geo_location = IpGeoLocationService.new
      begin
        @client_location = @geo_location.get_location(get_client_ip)
        @display_address = [@client_location['state_prov'], @client_location['district'], @client_location['city']].reject(&:blank?).join(", ")
      rescue
        flash[:alert] = 'something went wrong, we cannot get your current location, you can still make a post without it'
      end
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def default_posts_path
      posts_path
    end
end

app/views/posts/_form.html.erb
<style>
    p {
        font-size: 12px;
        margin-bottom: 4px
    }
</style>


<% if @display_address.present? %>
  <span class="badge bg-primary"><%= @display_address %></span>
    <div class="field">
      <div class="form-check form-switch">
        <%= check_box_tag :share_geo_location, 'true', @post.location.present?, class:"form-check-input", role:"switch"%>
        <label class="form-check-label">Share my location</label>
      </div>
    </div>
<% end %>

<div class="text-center">
  <%= image_tag "", id:"previewImg", class:"w-25 my-2 d-none", style:"object-fit: cover"%>
  <%= image_tag post.image.url, class:"original w-25 my-2", style:"object-fit: cover" if post.image?%>
  <div class="field">
    <%= f.label :image, "change image", class: "btn btn-dark" %>
    <%= f.file_field :image, class: 'form-control d-none', onchange: "previewFile(this)" %>
    <%= content_tag :p, post.errors.full_messages_for(:image).join(', '), class: 'text-danger m-1' if post.errors.has_key?(:image) %>
  </div>
</div>
<div class="field">
  <%= f.label :audience %>
  <%= f.select :audience, Post.audiences.keys.map { |key| [key.humanize, key] }, { :prompt => 'status' }, class: 'form-control  form-control-sm' %>
  <%= content_tag :p, post.errors.full_messages_for(:audience).join(', '), class: 'text-danger m-1' if post.errors.has_key?(:audience) %>
</div>
<div class="field">
  <%= f.label :text %>
  <%= f.text_field  :text , class: 'form-control' %>
  <%= content_tag :p, post.errors.full_messages_for(:text).join(', '), class: 'text-danger m-1' if post.errors.has_key?(:text) %>
</div>

<script>
    function previewFile(input) {
        var file = $("input[type=file]").get(0).files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function () {
                $("#previewImg").attr("src", reader.result);
                $("#previewImg").css('display', 'block');
                $(".original").css('display', 'none');
            }
            reader.readAsDataURL(file);
        }
    }
</script>

app/views/posts/edit.html.erb
<!--Page-->
<div class="container">
  <div class="card">
    <div class="card-header">
      <%= link_to "❮ Back", posts_path, class: 'btn btn-sm btn-outline-primary d-inline-block ' %>
      <h5 class="d-inline-block align-middle mx-2 my-1">Edit Post</h5>
    </div>
    <div class="card-body">
      <%= form_for @post, url: post_path(@post), method: :patch do |f| %>
        <%= render partial: 'form', locals: { f: f, post: @post } %>
        <%= f.submit "Update", class: 'border btn btn-primary form-control mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= link_to 'New', new_post_path, class: 'btn btn-primary w-25' %>
<div class="card mt-4">
  <div class="card-body ">
    <table class="table table-striped table-hover">
      <thead>
      <th>Image</th>
      <td>text</th>
      <td>city</th>
      <td>district</th>
      <td>province</th>
      <th>Action</th>
      </thead>
      <tbody>

      <% @posts.each do |post| %>
        <tr>
          <td style="width: 200px"><%= image_tag post.image.url, alt: 'avatar', class:'w-100',style:"object-fit: cover" if post.image?%></td>
          <td><%= post.text %></th>
          <td><%= post.city %></th>
          <td><%= post.district %></th>
          <td><%= post.province %></th>
          <td>
            <%= link_to 'comments', post_comments_path(post), class: 'btn btn-warning' %>
            <%= link_to 'edit', edit_post_path(post), class: 'btn btn-warning' if post.user == current_user %>
            <%= link_to "delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' if post.user == current_user %>
          </td>
        </tr>
      <% end %>
      <% unless @posts.present?%>
        <tr>
          <td colspan="4" class="text-muted">
            No posts to show
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/new.html.erb
<!--Page-->
<div class="container">
  <div class="card">
    <div class="card-header">
      <%= link_to "❮ Back", posts_path, class: 'btn btn-sm btn-outline-primary d-inline-block '%>
      <h5 class="d-inline-block align-middle mx-2 my-1">Create Post</h5>
    </div>
    <div class="card-body">
      <%= form_for @post, url: posts_path(@post), method: :post do |f| %>
        <%= render partial: 'form', locals: {f: f, post: @post} %>
        <%= f.submit "Create", class: 'border btn btn-primary form-control mt-3' %>
      <% end %>
    </div>
  </div>
</div>